sudo: required
services:
  - docker

before_install:
  - docker build -t orezimeteaching/client -f Dockerfile.dev .

script:
  - docker run orezimeteaching/client npm test -- --coverage
# after_sucess:
#   #build production grade dockerfile
#   - docker build -t orezimeteaching/client .
