sudo: required
services:
  - docker

before_install:
  - docker build -t orezimeteaching/client -f Dockerfile.dev .

script:
  - docker run -e CI=true orezimeteaching/client npm test -- --coverage

after_sucess:
  #build production grade dockerfile
  - docker build -t orezimeteaching/client .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push orezimeteaching/client
