version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - ./node_modules:/cleint/node_modules
      - ./:./client
    ports:
      - "3000:3000"
